# Generated by Django 6.0 on 2025-12-17 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_porte', models.CharField(max_length=10)),
                ('etage', models.IntegerField(default=0)),
                ('surface_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_local', models.CharField(choices=[('APPART', 'Appartement'), ('COMMERCE', 'Local Commercial'), ('PARKING', 'Parking'), ('BUREAU', 'Bureau')], default='APPART', max_length=20)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='core.immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('loyer_hc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Loyer HC')),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='core.local')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('est_payeur', models.BooleanField(default=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='core.bail')),
            ],
        ),
    ]
