# Generated by Django 6.0 on 2025-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='est_payeur',
        ),
        migrations.AddField(
            model_name='occupant',
            name='role',
            field=models.CharField(choices=[('LOCATAIRE', 'Locataire (Habitant)'), ('GARANT', 'Garant (Caution)')], default='LOCATAIRE', max_length=20),
        ),
    ]
