# Generated by Django 6.0 on 2025-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_occupant_est_payeur_occupant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='indice_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Indice IRL initial'),
        ),
        migrations.AddField(
            model_name='bail',
            name='soumis_tva',
            field=models.BooleanField(default=False, verbose_name='Soumis à la TVA'),
        ),
        migrations.AddField(
            model_name='bail',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='En % (ex: 20.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='bail',
            name='trimestre_reference',
            field=models.CharField(blank=True, help_text='Ex: T1 2024', max_length=20),
        ),
    ]
