# Generated by Django 6.0 on 2025-12-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bail_indice_reference_bail_soumis_tva_bail_taux_tva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom ou Raison Sociale')),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('type_proprietaire', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('SOCIETE', 'Société')], default='PARTICULIER', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immeubles', to='core.proprietaire', verbose_name='Propriétaire / Bailleur'),
        ),
    ]
