# Generated by Django 6.0 on 2025-12-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proprietaire_immeuble_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='type_charges',
            field=models.CharField(choices=[('PROVISION', 'Provision sur charges (Régularisation annuelle)'), ('FORFAIT', 'Forfait de charges (Pas de régularisation)')], default='PROVISION', max_length=20),
        ),
        migrations.CreateModel(
            name='CleRepartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Charges Générales, Eau Froide, Taxe Ordures Ménagères', max_length=100)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles_repartition', to='core.immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(help_text='Ex: Facture EDF Parties Communes', max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cle_repartition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.clerepartition')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Nombre de tantièmes ou m² pour ce local', max_digits=10)),
                ('cle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_parts', to='core.clerepartition')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_parts', to='core.local')),
            ],
            options={
                'unique_together': {('cle', 'local')},
            },
        ),
    ]
