# Generated by Django 6.0 on 2025-12-17 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bail_type_charges_clerepartition_depense_quotepart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bail',
            options={'verbose_name': 'Bail', 'verbose_name_plural': 'Baux'},
        ),
        migrations.AlterModelOptions(
            name='clerepartition',
            options={'verbose_name': 'Clé de répartition', 'verbose_name_plural': 'Clés de répartition'},
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='immeuble',
            options={'verbose_name': 'Immeuble', 'verbose_name_plural': 'Immeubles'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locaux'},
        ),
        migrations.AlterModelOptions(
            name='occupant',
            options={'verbose_name': 'Occupant', 'verbose_name_plural': 'Occupants'},
        ),
        migrations.AlterModelOptions(
            name='proprietaire',
            options={'verbose_name': 'Propriétaire', 'verbose_name_plural': 'Propriétaires'},
        ),
        migrations.AlterModelOptions(
            name='quotepart',
            options={'verbose_name': 'Quote-part', 'verbose_name_plural': 'Quote-parts'},
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bail',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Provisions charges'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='bail',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='depot_garantie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Dépôt de garantie'),
        ),
        migrations.AlterField(
            model_name='local',
            name='surface_m2',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Surface (m²)'),
        ),
        migrations.AlterField(
            model_name='local',
            name='type_local',
            field=models.CharField(choices=[('APPART', 'Appartement'), ('COMMERCE', 'Local Commercial'), ('PARKING', 'Parking'), ('BUREAU', 'Bureau')], default='APPART', max_length=20, verbose_name='Type de local'),
        ),
    ]
