# Generated by Django 6.0 on 2025-12-17 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bail_options_alter_clerepartition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerepartition',
            name='mode_repartition',
            field=models.CharField(choices=[('TANTIEMES', 'Par Tantièmes (Surface/Millièmes)'), ('CONSOMMATION', 'Par Consommation (Compteurs)')], default='TANTIEMES', max_length=20, verbose_name='Mode de calcul'),
        ),
        migrations.AddField(
            model_name='clerepartition',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Ex: Prix du m3 d'eau", max_digits=10, null=True, verbose_name='Prix Unitaire (si consommation)'),
        ),
        migrations.CreateModel(
            name='Ajustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text="La date détermine l'année de régularisation")),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé de la ligne')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Mettre un montant négatif pour une déduction', max_digits=8)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements', to='core.bail')),
            ],
            options={
                'verbose_name': 'Ajustement manuel',
                'verbose_name_plural': 'Ajustements manuels',
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField(default=django.utils.timezone.now, verbose_name='Date du relevé')),
                ('index_debut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancien Index')),
                ('index_fin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nouvel Index')),
                ('cle_repartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='core.clerepartition', verbose_name='Type de fluide')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='core.local')),
            ],
            options={
                'verbose_name': 'Relevé Compteur',
                'verbose_name_plural': 'Relevés Compteurs',
            },
        ),
    ]
