# Generated by Django 6.0 on 2025-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clerepartition_mode_repartition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='frequence_paiement',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel')], default='MENSUEL', max_length=20, verbose_name='Fréquence de paiement'),
        ),
    ]
