# Generated by Django 6.0 on 2025-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bail_frequence_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: Taxe foncière, TOM...', max_digits=8, verbose_name='Taxes (non soumises TVA)'),
        ),
    ]
