# Generated by Django 6.0 on 2025-12-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bail_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date du précédent relevé', null=True, verbose_name='Début période conso'),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Optionnel : Si la dépense couvre une période', null=True, verbose_name='Début période'),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin période'),
        ),
        migrations.CreateModel(
            name='Regularisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fait le')),
                ('date_debut', models.DateField(verbose_name='Début période')),
                ('date_fin', models.DateField(verbose_name='Fin période')),
                ('montant_reel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Réel')),
                ('montant_provisions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Provisions')),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde (A payer/Rendre)')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularisations', to='core.bail')),
            ],
        ),
    ]
