# Generated by Django 6.0 on 2026-01-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consommation_date_debut_depense_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularisation',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Régularisation', 'verbose_name_plural': 'Régularisations'},
        ),
        migrations.AddField(
            model_name='regularisation',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='regularisation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes / Commentaires'),
        ),
        migrations.AddField(
            model_name='regularisation',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
    ]
