# Generated by Django 6.0 on 2026-01-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_payment_tracking_to_regularisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BailTarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date d'entrée en vigueur de cette tarification", verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='None = encore active', null=True, verbose_name='Date de fin')),
                ('loyer_hc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Loyer HC')),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Provisions charges')),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Taxes')),
                ('indice_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Indice IRL/ILC')),
                ('trimestre_reference', models.CharField(blank=True, help_text='Ex: T1 2024', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('reason', models.CharField(blank=True, help_text='Ex: Révision IRL, Augmentation négociée, Tarification initiale', max_length=200, verbose_name='Motif du changement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='core.bail', verbose_name='Bail')),
            ],
            options={
                'verbose_name': 'Tarification',
                'verbose_name_plural': 'Tarifications',
                'ordering': ['-date_debut'],
            },
        ),
    ]
