# Generated by Django 6.0 on 2026-01-18 09:36

from django.db import migrations


def migrate_bail_tarifications(apps, schema_editor):
    """
    Crée une tarification initiale pour chaque bail existant,
    en utilisant les valeurs actuelles de loyer_hc, charges, taxes.
    """
    Bail = apps.get_model('core', 'Bail')
    BailTarification = apps.get_model('core', 'BailTarification')

    baux = Bail.objects.all()

    for bail in baux:
        # Date de début de la tarification = date de début du bail
        date_debut_tarif = bail.date_debut

        if date_debut_tarif is None:
            # Fallback si le bail n'a pas de date_debut
            from datetime import date
            date_debut_tarif = date(2020, 1, 1)
            print(f"WARNING: Bail {bail.id} sans date_debut, utilisation de {date_debut_tarif}")

        # Créer la tarification initiale
        BailTarification.objects.create(
            bail=bail,
            date_debut=date_debut_tarif,
            date_fin=None,  # Encore active
            loyer_hc=bail.loyer_hc,
            charges=bail.charges,
            taxes=bail.taxes,
            indice_reference=bail.indice_reference,
            trimestre_reference=bail.trimestre_reference or '',
            reason="Tarification initiale (migration automatique)",
            notes="Créée automatiquement lors de la migration vers le système d'historique tarifaire"
        )

    print(f"Migration: {baux.count()} tarifications initiales créées.")


def reverse_migration(apps, schema_editor):
    """
    Annulation: supprimer toutes les tarifications créées.
    """
    BailTarification = apps.get_model('core', 'BailTarification')
    count = BailTarification.objects.count()
    BailTarification.objects.all().delete()
    print(f"Rollback: {count} tarifications supprimées.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_create_bailtarification'),
    ]

    operations = [
        migrations.RunPython(migrate_bail_tarifications, reverse_migration),
    ]
