# Generated by Django 6.0 on 2026-01-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_bail_to_tarifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='indice_reference',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='loyer_hc',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='trimestre_reference',
        ),
    ]
