# Generated by Django 6.0 on 2026-01-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tarif_fields_from_bail'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeuble',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'acquisition"),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='frais_agence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Frais d'agence"),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='frais_notaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de notaire'),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Prix d'acquisition (frais inclus)"),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='regime_fiscal',
            field=models.CharField(choices=[('REVENUS_FONCIERS', 'Revenus Fonciers (Réel)'), ('MICRO_FONCIER', 'Micro-Foncier'), ('LMNP_REEL', 'LMNP Réel'), ('LMNP_MICRO', 'LMNP Micro-BIC'), ('LMP', 'LMP')], default='REVENUS_FONCIERS', max_length=20, verbose_name='Régime fiscal'),
        ),
        migrations.CreateModel(
            name='Amortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('IMMEUBLE', 'Immeuble (bâti)'), ('MOBILIER', 'Mobilier'), ('TRAVAUX', 'Travaux')], max_length=20, verbose_name='Type de bien')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('valeur_origine', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Valeur d'origine (€)")),
                ('date_mise_service', models.DateField(verbose_name='Date de mise en service')),
                ('duree_amortissement', models.PositiveIntegerField(verbose_name="Durée d'amortissement (années)")),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortissements', to='core.immeuble')),
            ],
            options={
                'verbose_name': 'Amortissement',
                'verbose_name_plural': 'Amortissements',
            },
        ),
        migrations.CreateModel(
            name='ChargeFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charge', models.CharField(choices=[('INTERETS', "Intérêts d'emprunt"), ('ASSURANCE_EMPRUNT', 'Assurance emprunt'), ('ASSURANCE_PNO', 'Assurance PNO'), ('TRAVAUX', 'Travaux'), ('TAXE_FONCIERE', 'Taxe foncière'), ('FRAIS_GESTION', 'Frais de gestion'), ('FRAIS_COMPTABLE', 'Frais comptables'), ('FRAIS_COPROPRIETE', 'Charges copropriété non récupérables'), ('AUTRES', 'Autres charges')], max_length=30, verbose_name='Type de charge')),
                ('annee', models.PositiveIntegerField(verbose_name='Année fiscale')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libellé détaillé')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_fiscaux/', verbose_name='Justificatif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_fiscales', to='core.immeuble')),
            ],
            options={
                'verbose_name': 'Charge fiscale',
                'verbose_name_plural': 'Charges fiscales',
                'ordering': ['-annee', 'type_charge'],
            },
        ),
        migrations.CreateModel(
            name='CreditImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('numero_pret', models.CharField(blank=True, max_length=50, verbose_name='Numéro de prêt')),
                ('capital_emprunte', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital emprunté (€)')),
                ('taux_interet', models.DecimalField(decimal_places=3, help_text='Ex: 2.5 pour 2,5%', max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('date_debut', models.DateField(verbose_name='Date de début du prêt')),
                ('type_credit', models.CharField(choices=[('AMORTISSABLE', 'Amortissable'), ('IN_FINE', 'In Fine')], default='AMORTISSABLE', max_length=20)),
                ('assurance_mensuelle', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Assurance mensuelle (€)')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.immeuble')),
            ],
            options={
                'verbose_name': 'Crédit immobilier',
                'verbose_name_plural': 'Crédits immobiliers',
            },
        ),
        migrations.CreateModel(
            name='EstimationValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_estimation', models.DateField(verbose_name="Date de l'estimation")),
                ('valeur_estimee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur estimée (€)')),
                ('source', models.CharField(choices=[('MANUELLE', 'Estimation manuelle'), ('AGENT', 'Agent immobilier'), ('NOTAIRE', 'Notaire'), ('DVF', 'Données DVF')], default='MANUELLE', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Commentaires')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='core.immeuble')),
            ],
            options={
                'verbose_name': 'Estimation de valeur',
                'verbose_name_plural': 'Estimations de valeur',
                'ordering': ['-date_estimation'],
            },
        ),
        migrations.CreateModel(
            name='VacanceLocative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début de vacance')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin de vacance')),
                ('motif', models.CharField(choices=[('TRAVAUX', 'Travaux'), ('RECHERCHE', 'Recherche de locataire'), ('DELIBERE', 'Vacance délibérée'), ('AUTRE', 'Autre')], default='RECHERCHE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacances', to='core.local')),
            ],
            options={
                'verbose_name': 'Vacance locative',
                'verbose_name_plural': 'Vacances locatives',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EcheanceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('numero_echeance', models.PositiveIntegerField(verbose_name='N° échéance')),
                ('capital_rembourse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capital remboursé')),
                ('interets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Intérêts')),
                ('assurance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Assurance')),
                ('capital_restant_du', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital restant dû')),
                ('payee', models.BooleanField(default=False, verbose_name='Payée')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='core.creditimmobilier')),
            ],
            options={
                'verbose_name': 'Échéance de crédit',
                'verbose_name_plural': 'Échéances de crédit',
                'ordering': ['credit', 'numero_echeance'],
                'unique_together': {('credit', 'numero_echeance')},
            },
        ),
    ]
