# Generated by Django 6.0 on 2026-02-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_patrimoine_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together={('cle', 'local')},
        ),
    ]
