# Generated by Django 5.2.11 on 2026-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_quotepart_unique_together"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bailtarification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_fin__isnull", True)),
                fields=("bail",),
                name="one_active_tarification_per_bail",
            ),
        ),
    ]
