# Generated by Django 5.2.17 on 2026-08-19 13:31

from django.db import migrations, models


def supprimer_regularisations_en_double(apps, schema_editor):
    """Nettoie l'historique avant de poser la contrainte d'unicite.

    Avant ce correctif, regenerer un PDF de regularisation creait une ligne
    supplementaire pour la meme periode. On ne garde que la plus recente de
    chaque groupe (bail, date_debut, date_fin).
    """
    Regularisation = apps.get_model('core', 'Regularisation')

    vus = set()
    a_supprimer = []
    for regul in Regularisation.objects.order_by('-date_creation', '-id'):
        cle = (regul.bail_id, regul.date_debut, regul.date_fin)
        if cle in vus:
            a_supprimer.append(regul.pk)
        else:
            vus.add(cle)

    if a_supprimer:
        Regularisation.objects.filter(pk__in=a_supprimer).delete()


def ne_rien_faire(apps, schema_editor):
    """Les doublons supprimes ne sont pas restaurables."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_bailtarification_one_active_tarification_per_bail"),
    ]

    operations = [
        migrations.RunPython(
            supprimer_regularisations_en_double, ne_rien_faire
        ),
        migrations.AlterField(
            model_name="immeuble",
            name="prix_achat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Prix d'achat (hors frais)",
            ),
        ),
        migrations.AddConstraint(
            model_name="regularisation",
            constraint=models.UniqueConstraint(
                fields=("bail", "date_debut", "date_fin"),
                name="une_regularisation_par_periode",
            ),
        ),
    ]
